# Generated by Django 4.2.6 on 2023-11-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshop.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='bookshop.city'),
        ),
    ]
